In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim

# **Tutorial**

In [3]:
torch.manual_seed(1)

In [4]:
lstm = nn.LSTM(3,3)

In [5]:
inputs = [torch.rand(1,3) for _ in range(5)]
print(inputs)

[tensor([[0.6705, 0.5896, 0.2873]]), tensor([[0.3486, 0.9579, 0.4075]]), tensor([[0.7819, 0.7165, 0.1768]]), tensor([[0.0748, 0.9799, 0.5261]]), tensor([[0.8427, 0.6036, 0.6608]])]


In [6]:
hidden = (
    torch.randn(1,1,3),
    torch.randn(1,1,3)
)
hidden

(tensor([[[ 0.9183, -0.0703,  1.1469]]]),
 tensor([[[-0.1082,  0.8635,  0.8067]]]))

In [7]:
inputs[0],inputs[0].view(1,1,-1)

(tensor([[0.6705, 0.5896, 0.2873]]), tensor([[[0.6705, 0.5896, 0.2873]]]))

In [8]:
for i in inputs:
    out,hidden = lstm(i.view(1,1,-1),hidden)

In [9]:
print(out)
print(hidden)

tensor([[[-0.0043, -0.2319, -0.0448]]], grad_fn=<MkldnnRnnLayerBackward0>)
(tensor([[[-0.0043, -0.2319, -0.0448]]], grad_fn=<StackBackward0>), tensor([[[-0.0089, -0.4142, -0.2258]]], grad_fn=<StackBackward0>))


Lets begin the project

In [10]:
lstm = nn.LSTM(96,1)

In [22]:
inputs = [torch.rand(1,96) for _ in range(20)]
print(inputs)

[tensor([[0.2522, 0.3368, 0.9558, 0.0553, 0.7386, 0.0506, 0.2615, 0.3982, 0.5346,
         0.4188, 0.2714, 0.2770, 0.1959, 0.1510, 0.1885, 0.9795, 0.2644, 0.0842,
         0.8437, 0.6940, 0.8439, 0.0027, 0.0241, 0.1451, 0.2366, 0.4989, 0.7163,
         0.7927, 0.0699, 0.6994, 0.2108, 0.6149, 0.6570, 0.5800, 0.6769, 0.4750,
         0.8301, 0.6043, 0.9380, 0.6084, 0.2353, 0.8211, 0.5271, 0.9832, 0.4447,
         0.9947, 0.2081, 0.7513, 0.1270, 0.8433, 0.5908, 0.7839, 0.0694, 0.0026,
         0.7409, 0.2943, 0.6980, 0.2034, 0.3454, 0.5022, 0.8011, 0.7824, 0.4553,
         0.3586, 0.4913, 0.7577, 0.0762, 0.3472, 0.0180, 0.5722, 0.4409, 0.7832,
         0.8994, 0.0725, 0.2787, 0.4196, 0.4950, 0.3859, 0.1856, 0.3068, 0.4871,
         0.9021, 0.3726, 0.8302, 0.0958, 0.5224, 0.1098, 0.0308, 0.5496, 0.2711,
         0.8681, 0.8949, 0.0023, 0.4652, 0.4146, 0.2150]]), tensor([[0.1509, 0.2884, 0.7208, 0.6189, 0.8009, 0.4702, 0.7597, 0.5967, 0.3910,
         0.4708, 0.0453, 0.4885, 0.3357, 0.3327,

In [23]:
hidden = (
    torch.randn(1,1,1),
    torch.randn(1,1,1)
)
hidden

(tensor([[[-0.5027]]]), tensor([[[-0.4132]]]))

In [24]:
for i in inputs:
    out,hidden = lstm(i.view(1,1,-1),hidden)

In [25]:
out,hidden

(tensor([[[0.2369]]], grad_fn=<MkldnnRnnLayerBackward0>),
 (tensor([[[0.2369]]], grad_fn=<StackBackward0>),
  tensor([[[0.2429]]], grad_fn=<StackBackward0>)))