In [59]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim

# **Tutorial**

In [60]:
torch.manual_seed(1)

In [61]:
lstm = nn.LSTM(3,3)

In [62]:
inputs = [torch.rand(1,3) for _ in range(5)]
print(inputs)

[tensor([[0.6705, 0.5896, 0.2873]]), tensor([[0.3486, 0.9579, 0.4075]]), tensor([[0.7819, 0.7165, 0.1768]]), tensor([[0.0748, 0.9799, 0.5261]]), tensor([[0.8427, 0.6036, 0.6608]])]


In [63]:
hidden = (
    torch.randn(1,1,3),
    torch.randn(1,1,3)
)
hidden

(tensor([[[ 0.9183, -0.0703,  1.1469]]]),
 tensor([[[-0.1082,  0.8635,  0.8067]]]))

In [64]:
inputs[0],inputs[0].view(1,1,-1)

(tensor([[0.6705, 0.5896, 0.2873]]), tensor([[[0.6705, 0.5896, 0.2873]]]))

In [65]:
for i in inputs:
    out,hidden = lstm(i.view(1,1,-1),hidden)

In [66]:
print(out)
print(hidden)

tensor([[[-0.0043, -0.2319, -0.0448]]], grad_fn=<MkldnnRnnLayerBackward0>)
(tensor([[[-0.0043, -0.2319, -0.0448]]], grad_fn=<StackBackward0>), tensor([[[-0.0089, -0.4142, -0.2258]]], grad_fn=<StackBackward0>))


Lets begin the project